/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Niyama Design System Colors - New Brutalist
        'niyama-black': '#000000',
        'niyama-white': '#ffffff',
        'niyama-gray': {
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
        },
        'niyama-accent': '#ff6b35',
        'niyama-accent-dark': '#e55a2b',
        'niyama-accent-light': '#ff8c69',
        'niyama-success': '#ff6b35',
        'niyama-success-light': '#dcfce7',
        'niyama-success-dark': '#16a34a',
        'niyama-green': '#ff6b35',
        'niyama-green-light': '#dcfce7',
        'niyama-green-dark': '#16a34a',
        'niyama-warning': '#f59e0b',
        'niyama-warning-light': '#fef3c7',
        'niyama-warning-dark': '#d97706',
        'niyama-yellow': '#f59e0b',
        'niyama-yellow-light': '#fef3c7',
        'niyama-yellow-dark': '#d97706',
        'niyama-red': '#ef4444',
        'niyama-red-light': '#fee2e2',
        'niyama-red-dark': '#dc2626',
        'niyama-error': '#ef4444',
        'niyama-error-light': '#fee2e2',
        'niyama-error-dark': '#dc2626',
        'niyama-info': '#ff6b35',
        'niyama-info-light': '#dbeafe',
        'niyama-info-dark': '#2563eb',
        'niyama-purple': '#8b5cf6',
        'niyama-purple-light': '#ede9fe',
        'niyama-purple-dark': '#7c3aed',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'Monaco', 'monospace'],
        display: ['Space Grotesk', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'heading-1': ['2.5rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-2': ['2rem', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-3': ['1.5rem', { lineHeight: '1.4', fontWeight: '500' }],
        'body-large': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'caption': ['0.875rem', { lineHeight: '1.5', fontWeight: '500' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      borderRadius: {
        'none': '0',
        'sm': '2px',
        'base': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0, 0, 0, 0.1)',
        'modal': '0 10px 25px rgba(0, 0, 0, 0.15)',
        'dropdown': '0 4px 12px rgba(0, 0, 0, 0.15)',
        'brutal': '4px 4px 0px 0px #000000',
        'brutal-lg': '8px 8px 0px 0px #000000',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};