apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: niyama

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - network-policy.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/name: niyama
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: platform

images:
  - name: niyama/backend
    newTag: latest
  - name: niyama/frontend
    newTag: latest
