apiVersion: v1
kind: ConfigMap
metadata:
  name: niyama-frontend-config
  namespace: niyama
data:
  VITE_API_URL: "https://api.niyama.dev"
  VITE_APP_NAME: "Niyama"
  VITE_APP_VERSION: "1.0.0"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: niyama-frontend
  namespace: niyama
  labels:
    app: niyama-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: niyama-frontend
  template:
    metadata:
      labels:
        app: niyama-frontend
    spec:
      containers:
      - name: niyama-frontend
        image: niyama/frontend:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: niyama-frontend-config
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: niyama-frontend
  namespace: niyama
  labels:
    app: niyama-frontend
spec:
  selector:
    app: niyama-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: niyama-frontend-hpa
  namespace: niyama
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: niyama-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
